#! /usr/bin/env python3                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
# Author: Han Soho                                                                                                                                                                                                                                              
# Description: Intended to retrieve SSL keys & certs from porkbun using their API                                                                                                                                                                               
                                                                                                                                                                                                                                                                
import requests, os, socket, ssl                                                                                                                                                                                                                                
from dotenv import load_dotenv, dotenv_values                                                                                                                                                                                                                   
from datetime import datetime                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
load_dotenv()                                                                                                                                                                                                                                                   

'''
Gets expiry date of SSL cert of specified hostname
'''
def get_ssl_expiry_date(hostname):                                                                                                                                                                                                                              
    # Define the context for the SSL connection                                                                                                                                                                                                                 
    context = ssl.create_default_context()                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                
    # Connect to the host using an SSL-wrapped socket                                                                                                                                                                                                           
    with socket.create_connection((hostname, 443)) as sock:                                                                                                                                                                                                     
        with context.wrap_socket(sock, server_hostname=hostname) as ssock:                                                                                                                                                                                      
            # Get the certificate                                                                                                                                                                                                                               
            cert = ssock.getpeercert()                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
    # Grab the expiry date from the certificate                                                                                                                                                                                                              
    expiry_date_str = cert['notAfter']                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
    # Convert expiry date string to a datetime obj                                                                                                                                                                                                           
    expiry_date = datetime.strptime(expiry_date_str, '%b %d %H:%M:%S %Y %Z')                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
    return expiry_date                                                                                                                                                                                                                                          


''' 
Checks SSL expiry, runs API req if expired or if hasnt been run before
'''
def check_ssl_certificate_expiry(hostname):                                                                                                                                                                                                                     
    expiry_date = get_ssl_expiry_date(hostname)                                                                                                                                                                                                                 
    current_date = datetime.utcnow()                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
    # Calculate the difference between the expiry date and the current date                                                                                                                                                                                     
    days_to_expiry = (expiry_date - current_date).days                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
    # SSL not expired                                                                                                                                                                                                                                           
    if days_to_expiry > 0:                                                                                                                                                                                                                                      
        home = os.getenv("HOME")                                                                                                                                                                                                                                
        cert_dir = f'{home}/ssl/certs/'                                                                                                                                                                                                                         
        checks = [ cert_dir, cert_dir+'intermediate_certificate.pem',cert_dir+'private_key.pem',cert_dir+'public_key.pem',cert_dir+"certificate_chain.pem" ]  

        # Check if SSL dir exists and if the keys and certs exist                                                                                                                                                                                               
        for check in checks:                                                                                                                                                                                                                                    
            # If even one of them doesnt exist run api req                                                                                                                                                                                                      
            if not os.path.exists(check):                                                                                                                                                                                                                       
                send_api_req()                                                                                                                                                                                                                                  
                break

    # Else certs have expired, renew                                                                                                                                                                                                                            
    else:                                                                                                                                                                                                                                                       
        send_api_req()                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                

''' 
Create the directory where the downloaded certs and keys will be held 
'''                                                                                                                                                                                                                                                                
def create_cert_root():                                                                                                                                                                                                                                         
    home = os.getenv("HOME")                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
    # If the Home env var is not set, cannot move forward                                                                                                                                                                                                       
    if home is None:                                                                                                                                                                                                                                            
        raise EnvironmentError("The HOME env var is not set.. exiting.")                                                                                                                                                                                        
        exit(1)                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                
    cert_dir = f'{home}/ssl/certs/'                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
    # If the path for the keys and certs doesnt exist, create it                                                                                                                                                                                                
    if not os.path.exists(cert_dir):                                                                                                                                                                                                                            
        os.makedirs(cert_dir)                                                                                                                                                                                                                                   
        print(f'Certificate directory {cert_dir} created.')                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                
    # Return cert directory path                                                                                                                                                                                                                                
    return cert_dir                                                                                                                                                                                                                                             

''' 
Send API request to download & store certs & keys 
'''
def send_api_req():                                                                                                                                                                                                                                             
    cdir = create_cert_root()                                                                                                                                                                                                                                   
    SEC_KEY = os.getenv("SEC_KEY")                                                                                                                                                                                                                              
    API_KEY = os.getenv("API_KEY")                                                                                                                                                                                                                              
    ENDPOINT = os.getenv("ENDPOINT")                                                                                                                                                                                                                            
    payload = {                                                                                                                                                                                                                                                 
        "secretapikey": SEC_KEY,                                                                                                                                                                                                                                
        "apikey": API_KEY                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
    # Send api request and capture response                                                                                                                                                                                                                     
    response = requests.post(ENDPOINT, json=payload)                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
    # If success                                                                                                                                                                                                                                                
    if response.ok:                                                                                                                                                                                                                                             
        # Parse keys from response and write them to the appropriate files                                                                                                                                                                                      
        data = response.json()                                                                                                                                                                                                                                  
        certs = [ "intermediatecertificate", "certificatechain", "privatekey", "publickey" ]                                                                                                                                                                    
        cert_fname = [ "intermediate_certificate.pem", "certificate_chain.pem", "private_key.pem", "public_key.pem" ]                                                                                                                                           
        i = 0                                                                                                                                                                                                                                                   
        for cert in certs:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            try:                                                                                                                                                                                                                                                
                with open(cdir+cert_fname[i], "w") as file:                                                                                                                                                                                                     
                    file.write(data.get(cert))
                    i += 1
            except Exception as e:                                                                                                                                                                                                                              
                print("Could not get and save certificates and keys. Exiting...")                                                                                                                                                                               
                exit(1)                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
        print("Certificates and keys saved.")                                                                                                                                                                                                                   
    else:                                                                                                                                                                                                                                                       
        print("Failed to get SSL cert:", response.text)                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
def __main__():                                                                                                                                                                                                                                                 
    try:                                                                                                                                                                                                                                                        
        check_ssl_certificate_expiry("DOMAIN_HERE")                                                                                                                                                                                                              
    except Exception as e:                                                                                                                                                                                                                                      
        print(f'An error occured: {e}')                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
if __name__ == "__main__":
   __main__()
